UniSchedule/Controllers/GiangViensController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UniSchedule.Models;

namespace UniSchedule.Controllers
{
    public class GiangViensController : Controller
    {
        private XepLichGiangVienEntities db = new XepLichGiangVienEntities();
        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            if (Session["MaVaiTro"] == null || (int)Session["MaVaiTro"] != 0)
            {
                // Không phải GiaoVu thì chuyển về trang login
                filterContext.Result = RedirectToAction("Login", "Home");
            }
            base.OnActionExecuting(filterContext);
        }
        // GET: GiangViens
        public ActionResult Index()
        {


            var giangViens = db.GiangViens
                .Include(g => g.Khoa)
                .Include(g => g.PhanCongGiangDays.Select(p => p.LopHocPhan));
            return View(giangViens.ToList());
        }

        // GET: GiangViens/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GiangVien giangVien = db.GiangViens.Find(id);
            if (giangVien == null)
            {
                return HttpNotFound();
            }
            return View(giangVien);
        }

        // GET: GiangViens/Create
        public ActionResult Create()
        {
            ViewBag.MaKhoa = new SelectList(db.Khoas, "MaKhoa", "TenKhoa");
            return View();
        }

        // POST: GiangViens/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaGV,TenGV,MaKhoa,Email,SoDienThoai")] GiangVien giangVien)
        {
            if (ModelState.IsValid)
            {
                ModelState.AddModelError("", "Thiếu thông tin.");
                if ((giangVien.MaGV == null || giangVien.MaGV == "") || (giangVien.TenGV == null || giangVien.TenGV == "") || (giangVien.Email == null || giangVien.Email == "") || (giangVien.SoDienThoai == null || giangVien.SoDienThoai == "") || (giangVien.MaKhoa == null || giangVien.MaKhoa == ""))
                {
                    if (giangVien.MaGV == null || giangVien.MaGV == "")
                    {
                        ModelState.AddModelError("MaGV", "Mã giảng viên không được để trống.");
                    }
                    if (giangVien.TenGV == null || giangVien.TenGV == "")
                    {
                        ModelState.AddModelError("TenGV", "Tên giảng viên không được để trống.");
                    }
                    if (giangVien.MaKhoa == null || giangVien.MaKhoa == "")
                    {
                        ModelState.AddModelError("MaKhoa", "Chọn một khoa cho giảng viên");
                    }
                    if (giangVien.Email == null || giangVien.Email == "")
                    {
                        ModelState.AddModelError("Email", "Email không được để trống.");
                    }
                    if (giangVien.SoDienThoai == null || giangVien.SoDienThoai == "")
                    {
                        ModelState.AddModelError("SoDienThoai", "Số điện thoại không được để trống.");
                    }
                    ViewBag.MaKhoa = new SelectList(db.Khoas, "MaKhoa", "TenKhoa", giangVien.MaKhoa);
                    return View(giangVien);
                }


                bool isExist = db.GiangViens.Any(g => g.MaGV == giangVien.MaGV);
                if (isExist)
                {
                    ModelState.AddModelError("", "Mã giảng viên đã tồn tại.");
                    ModelState.AddModelError("MaGV", "Nhập một mã giảng viên khác.");
                    ViewBag.MaKhoa = new SelectList(db.Khoas, "MaKhoa", "TenKhoa", giangVien.MaKhoa);
                    return View(giangVien);
                }

                db.GiangViens.Add(giangVien);
                TempData["SuccessMessage"] = "Thêm thành công!!";
                TaiKhoan taiKhoan = new TaiKhoan
                {
                    TenDangNhap = giangVien.SoDienThoai,
                    MatKhau = "123abc",
                    MaGV = giangVien.MaGV,
                    MaVaiTro = 1
                };

                db.TaiKhoans.Add(taiKhoan);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            ViewBag.MaKhoa = new SelectList(db.Khoas, "MaKhoa", "TenKhoa", giangVien.MaKhoa);
            return View(giangVien);
        }



        // GET: GiangViens/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GiangVien giangVien = db.GiangViens.Find(id);
            if (giangVien == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaKhoa = new SelectList(db.Khoas, "MaKhoa", "TenKhoa", giangVien.MaKhoa);
            return View(giangVien);
        }

        // POST: GiangViens/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaGV,TenGV,MaKhoa,Email,SoDienThoai")] GiangVien giangVien)
        {
            if ((giangVien.TenGV == null || giangVien.TenGV == "") || (giangVien.Email == null || giangVien.Email == "") || (giangVien.SoDienThoai == null || giangVien.SoDienThoai == ""))
            {
                if (giangVien.TenGV == null || giangVien.TenGV == "")
                {
                    ModelState.AddModelError("TenGV", "Tên Giảng Viên không được để trống.");
                }
                if (giangVien.Email == null || giangVien.Email == "")
                {
                    ModelState.AddModelError("Email", "Email không được để trống.");
                }
                if (giangVien.SoDienThoai == null || giangVien.SoDienThoai == "")
                {
                    ModelState.AddModelError("SoDienThoai", "Số điện thoại không được để trống");
                }
            }

            if (ModelState.IsValid)
            {
                db.Entry(giangVien).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaKhoa = new SelectList(db.Khoas, "MaKhoa", "TenKhoa", giangVien.MaKhoa);
            return View(giangVien);
        }

        // GET: GiangViens/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GiangVien giangVien = db.GiangViens.Find(id);
            if (giangVien == null)
            {
                return HttpNotFound();
            }
            return View(giangVien);
        }

        // POST: GiangViens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            GiangVien giangVien = db.GiangViens.Find(id);

            bool isTeacherHaveClass = db.PhanCongGiangDays.Any(p => p.MaGV == id);
            if (isTeacherHaveClass)
            {
                ModelState.AddModelError("", "Không thể xóa giảng viên này vì đã có phân công giảng dạy.");
                return View(giangVien);
            }

            bool isIdNotValid = db.TaiKhoans.Any(t => t.MaGV == id);
            if (isIdNotValid)
            {
                ModelState.AddModelError("", "Không thể xóa giảng viên này vì đã có tài khoản.");
                return View(giangVien);
            }
            db.GiangViens.Remove(giangVien);
            db.SaveChanges();
            TempData.Add("SuccessMessage", "Xóa thành công!!");
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UniSchedule/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniSchedule.Models;


namespace XepLichGiangVien.Controllers
{
    public class HomeController : Controller
    {
        private XepLichGiangVienEntities db = new XepLichGiangVienEntities();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(string tenDangNhap, string matKhau)
        {
            var taiKhoan = db.TaiKhoans.FirstOrDefault(t => t.TenDangNhap == tenDangNhap && t.MatKhau == matKhau);
            if (taiKhoan != null)
            {
                Session["TenDangNhap"] = taiKhoan.TenDangNhap;
                Session["MaVaiTro"] = taiKhoan.MaVaiTro;
                Session["MaGV"] = taiKhoan.MaGV;

                if (taiKhoan.MaVaiTro == 0)
                {
                    return RedirectToAction("GiaoVu", "Home");
                }
                else if (taiKhoan.MaVaiTro == 1)
                {
                    return RedirectToAction("GiangVien", "Home");
                }
            }
            else
            {
                ViewBag.Error = "Tên đăng nhập hoặc mật khẩu không đúng.";
                return View();
            }

            return View();
        }

        public ActionResult GiaoVu()
        {
            if (Session["MaVaiTro"] == null || (int)Session["MaVaiTro"] != 0)
            {
                return RedirectToAction("Login", "Home");
            }
            return View();
        }
        public ActionResult GiangVien()
        {
            if (Session["MaVaiTro"] == null || (int)Session["MaVaiTro"] != 1)
            {
                return RedirectToAction("Login", "Home");
            }
            return View();
        }
        public ActionResult ThongTinCaNhan()
        {
            if (Session["MaGV"] == null)
            {
                return RedirectToAction("Login", "Home");
            }

            string maGV = Session["MaGV"].ToString();
            var giangVien = db.GiangViens.FirstOrDefault(gv => gv.MaGV == maGV);

            if (giangVien == null)
            {
                return HttpNotFound("Không tìm thấy thông tin giảng viên.");
            }

            return View(giangVien);
        }

        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Login", "Home");
        }
    }
}

UniSchedule/Controllers/KhoasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UniSchedule.Models;

namespace UniSchedule.Controllers
{
    public class KhoasController : Controller
    {
        private XepLichGiangVienEntities db = new XepLichGiangVienEntities();
        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            if (Session["MaVaiTro"] == null || (int)Session["MaVaiTro"] != 0)
            {
                // Không phải GiaoVu thì chuyển về trang login
                filterContext.Result = RedirectToAction("Login", "Home");
            }
            base.OnActionExecuting(filterContext);
        }
        // GET: Khoas
        public ActionResult Index()
        {
            return View(db.Khoas.ToList());
        }

        // GET: Khoas/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Khoa khoa = db.Khoas.Find(id);
            if (khoa == null)
            {
                return HttpNotFound();
            }
            return View(khoa);
        }

        // GET: Khoas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Khoas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaKhoa,TenKhoa")] Khoa khoa)
        {
            bool isExist = db.Khoas.Any(k => k.MaKhoa == khoa.MaKhoa);
            if (isExist)
            {
                ModelState.AddModelError("MaKhoa", "Mã khoa đã tồn tại.");
                ModelState.AddModelError("", "Mã khoa đã tồn tại.");
                return View(khoa);
            }

            if ((khoa.MaKhoa == null || khoa.MaKhoa == "") || (khoa.TenKhoa == null || khoa.TenKhoa == ""))
            {
                ModelState.AddModelError("", "Thiếu thông tin");
                if (khoa.MaKhoa == null || khoa.MaKhoa == "")
                {
                    ModelState.AddModelError("MaKhoa", "Mã khoa không được để trống");
                }
                if (khoa.TenKhoa == null || khoa.TenKhoa == "")
                {
                    ModelState.AddModelError("TenKhoa", "Điền tên khoa.");
                }
                return View(khoa);
            }

            if (ModelState.IsValid)
            {

                db.Khoas.Add(khoa);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(khoa);
        }

        // GET: Khoas/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Khoa khoa = db.Khoas.Find(id);
            if (khoa == null)
            {
                return HttpNotFound();
            }
            return View(khoa);
        }

        // POST: Khoas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaKhoa,TenKhoa")] Khoa khoa)
        {
            bool isExist = db.Khoas.Any(k => k.MaKhoa == khoa.MaKhoa && k.MaKhoa != khoa.MaKhoa);
            if (isExist)
            {
                ModelState.AddModelError("MaKhoa", "Mã khoa đã tồn tại.");
            }
            if (ModelState.IsValid)
            {
                db.Entry(khoa).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(khoa);
        }

        // GET: Khoas/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Khoa khoa = db.Khoas.Find(id);
            if (khoa == null)
            {
                return HttpNotFound();
            }
            return View(khoa);
        }

        // POST: Khoas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            bool isExist = db.GiangViens.Any(gv => gv.MaKhoa == id);
            if (isExist)
            {
                ModelState.AddModelError("", "Không thể xóa khoa này vì có giảng viên thuộc khoa này.");
                return RedirectToAction("Index");
            }

            Khoa khoa = db.Khoas.Find(id);
            db.Khoas.Remove(khoa);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UniSchedule/Views/Home/GiangVien.cshtml
@{
    ViewBag.Title = "Trang Giảng Viên";
}

<!-- Thêm link FontAwesome nếu chưa có -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" />

<div class="container d-flex justify-content-center align-items-center min-vh-100">
    <div class="card shadow-lg p-4" style="width: 100%; max-width: 500px; border-radius: 1rem;">
        <div class="text-center mb-4">
            <h2 class="fw-bold">Chào mừng Giảng Viên</h2>
            <p class="text-muted">Vui lòng chọn chức năng</p>
        </div>

        <div class="list-group">
            <a href="@Url.Action("XemLich", "LichDays")" class="list-group-item list-group-item-action d-flex align-items-center gap-2">
                <i class="fas fa-calendar-alt fa-lg text-primary"></i> Xem lịch dạy
            </a>
            <a href="@Url.Action("ThongTinCaNhan", "Home")" class="list-group-item list-group-item-action d-flex align-items-center gap-2">
                <i class="fas fa-user fa-lg text-success"></i> Thông tin cá nhân
            </a>
        </div>

        <div class="text-center mt-4">
            <a href="@Url.Action("Logout", "Home")" class="btn btn-outline-danger w-100">
                <i class="fas fa-sign-out-alt"></i> Đăng xuất
            </a>
        </div>
    </div>
</div>

<style>
    .list-group-item {
        transition: background-color 0.3s, transform 0.3s;
        border: none;
        border-bottom: 1px solid #eee;
    }

        .list-group-item:hover {
            background-color: #f8f9fa;
            transform: translateX(5px);
        }

    .card {
        background: #ffffff;
    }
</style>

UniSchedule/Views/Home/GiaoVu.cshtml
@model IEnumerable<UniSchedule.Models.LichDay>

@{
    ViewBag.Title = "Trang Giáo Vụ";
}

<!-- Thêm link FontAwesome nếu chưa có -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" />

<div class="container d-flex justify-content-center align-items-center min-vh-100">
    <div class="card shadow-lg p-4" style="width: 100%; max-width: 500px; border-radius: 1rem;">
        <div class="text-center mb-4">
            <h2 class="fw-bold">Chào mừng Giáo Vụ</h2>
            <p class="text-muted">Vui lòng chọn chức năng</p>
        </div>

        <div class="list-group">
            <a href="@Url.Action("Index", "Khoas")" class="list-group-item list-group-item-action d-flex align-items-center gap-2">
                <i class="fas fa-building fa-lg text-primary"></i> Quản lý Khoa
            </a>
            <a href="@Url.Action("Index", "GiangViens")" class="list-group-item list-group-item-action d-flex align-items-center gap-2">
                <i class="fas fa-chalkboard-teacher fa-lg text-success"></i> Quản lý Giảng viên
            </a>
            <a href="@Url.Action("Index", "LopHocPhans")" class="list-group-item list-group-item-action d-flex align-items-center gap-2">
                <i class="fas fa-book-open fa-lg text-warning"></i> Quản lý Lớp học phần
            </a>
            <a href="@Url.Action("Index", "PhongHocs")" class="list-group-item list-group-item-action d-flex align-items-center gap-2">
                <i class="fas fa-door-open fa-lg text-info"></i> Quản lý Phòng học
            </a>
            <a href="@Url.Action("Index", "PhanCongGiangDays")" class="list-group-item list-group-item-action d-flex align-items-center gap-2">
                <i class="fas fa-chalkboard-teacher fa-lg text-warning"></i> Phân Công Giảng Dạy
            </a>
            <a href="@Url.Action("Index", "LichDays")" class="list-group-item list-group-item-action d-flex align-items-center gap-2">
                <i class="fas fa-calendar-alt fa-lg text-danger"></i> Xếp Thời Khóa Biểu
            </a>
            <a href="@Url.Action("XemLich", "LichDays")" class="list-group-item list-group-item-action d-flex align-items-center gap-2">
                <i class="fas fa-calendar-check fa-lg text-primary"></i> Xem Lịch Cá Nhân
            </a>
            <a href="@Url.Action("Index", "TaiKhoans")" class="list-group-item list-group-item-action d-flex align-items-center gap-2">
                <i class="fas fa-user-cog fa-lg text-secondary"></i> Quản lý Tài khoản
            </a>
        </div>

        <div class="text-center mt-4">
            <a href="@Url.Action("Logout", "Home")" class="btn btn-outline-danger w-100">
                <i class="fas fa-sign-out-alt"></i> Đăng xuất
            </a>
        </div>
    </div>
</div>

<style>
    .list-group-item {
        transition: background-color 0.3s, transform 0.3s;
        border: none;
        border-bottom: 1px solid #eee;
    }

        .list-group-item:hover {
            background-color: #f8f9fa;
            transform: translateX(5px);
        }

    .card {
        background: #ffffff;
    }
</style>

UniSchedule/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Trang chủ";
    Layout = "~/Views/Shared/_Layout.cshtml"; // hoặc để trống nếu bạn không dùng layout
}

<style>
    body {
        background: url('https://baodanang.vn/dataimages/202111/original/images1630532_3__H_N_.jpg') no-repeat center center fixed;
        background-size: cover;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }

    .homepage-container {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        height: 80vh;
        text-align: center;
        background: rgba(255, 255, 255, 0.7); /* Để nền mờ đi, dễ đọc chữ */
        padding: 20px;
        border-radius: 10px;
    }

    .homepage-title {
        font-size: 3rem;
        margin-bottom: 0.5rem;
        color: #333;
    }

    .homepage-subtitle {
        font-size: 1.2rem;
        margin-bottom: 2rem;
        color: #666;
    }

    .login-button {
        padding: 0.75rem 2rem;
        font-size: 1.2rem;
        background-color: #007bff;
        color: white;
        border: none;
        border-radius: 8px;
        text-decoration: none;
        transition: background-color 0.3s ease;
    }

        .login-button:hover {
            background-color: #0056b3;
            color: white;
        }
</style>

<div class="homepage-container">
    <img src="https://inkythuatso.com/uploads/thumbnails/800/2021/12/logo-dai-hoc-bach-khoa-da-nang-inkythuatso-01-21-09-26-41.jpg" alt="Logo" style="width: 150px; height: auto; margin-bottom: 20px;" />
    <div class="homepage-title">Ứng Dụng Xếp Lịch Tự Động</div>
    <div class="homepage-subtitle">Trường Đại Học Bách Khoa - Đại Học Đà Nẵng</div>

    @if (Session["TenDangNhap"] != null)
    {
        @Html.ActionLink(
            "Đăng xuất",
            "Logout",
            "Home",
            routeValues: null,
            htmlAttributes: new { @class = "login-button" }
        )
    }
    else
    {
        @Html.ActionLink(
            "Đăng nhập",
            "Login",
            "Home",
            routeValues: null,
            htmlAttributes: new { @class = "login-button" }
        )
    }
</div>

UniSchedule/Views/Home/Login.cshtml
@{
    ViewBag.Title = "Đăng nhập";
}

<style>
    body {
        background: #f0f2f5;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }

    .login-container {
        max-width: 400px;
        margin: 80px auto;
        padding: 40px 30px;
        background-color: #fff;
        border-radius: 12px;
        box-shadow: 0px 8px 16px rgba(0,0,0,0.1);
    }

        .login-container h2 {
            text-align: center;
            margin-bottom: 30px;
            color: #333;
        }

    .form-group {
        position: relative;
        margin-bottom: 20px;
    }

        .form-group input[type="text"],
        .form-group input[type="password"] {
            width: 100%;
            padding: 12px 40px 12px 40px; /* Padding cho icon 2 bên */
            border: 1px solid #ccc;
            border-radius: 8px;
            height: 45px;
            box-sizing: border-box;
            font-size: 14px;
        }

        .form-group i.fa-user,
        .form-group i.fa-lock {
            position: absolute;
            top: 50%;
            left: 12px;
            transform: translateY(-50%);
            color: #888;
            font-size: 18px;
        }

    .toggle-password {
        position: absolute;
        top: 50%;
        right: 12px;
        transform: translateY(-50%);
        cursor: pointer;
        color: #888;
        font-size: 18px;
    }

    button {
        width: 100%;
        padding: 12px;
        background-color: #4CAF50;
        color: white;
        border: none;
        border-radius: 8px;
        font-size: 16px;
        font-weight: bold;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

        button:hover {
            background-color: #45a049;
        }

    .error-message {
        color: red;
        text-align: center;
        margin-bottom: 20px;
    }
</style>

<div class="login-container">
    <h2>Đăng nhập</h2>

    @if (ViewBag.Error != null)
    {
        <div class="error-message">@ViewBag.Error</div>
    }

    @using (Html.BeginForm("Login", "Home", FormMethod.Post))
    {
        <div class="form-group">
            <i class="fas fa-user"></i>
            @Html.TextBox("tenDangNhap", null, new { @placeholder = "Tên đăng nhập", @class = "form-control" })
        </div>

        <div class="form-group">
            <i class="fas fa-lock"></i> <!-- Icon khoá bên trái -->
            @Html.Password("matKhau", null, new { @placeholder = "Mật khẩu", @class = "form-control", @id = "password" })
            <i class="fas fa-eye toggle-password" id="togglePassword"></i> <!-- Icon con mắt bên phải -->
        </div>

        <div class="form-group">
            <button type="submit">Đăng nhập</button>
        </div>
        <div class="form-group">
            <a href="@Url.Action("Index", "Home")" class="btn btn-secondary" style="width: 100%; padding: 12px; background-color: #ccc; color: white; border: none; border-radius: 8px; font-size: 16px; font-weight: bold; cursor: pointer; transition: background-color 0.3s ease;">
                Quay lại trang chủ
            </a>
        </div>

    }
</div>

<!-- FontAwesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />

<!-- JavaScript: hiện/ẩn mật khẩu -->
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const togglePassword = document.getElementById('togglePassword');
        const passwordField = document.getElementById('password');

        togglePassword.addEventListener('click', function () {
            // Kiểm tra hiện tại là password hay text
            const type = passwordField.getAttribute('type') === 'password' ? 'text' : 'password';
            passwordField.setAttribute('type', type);

            // Đổi icon
            this.classList.toggle('fa-eye');
            this.classList.toggle('fa-eye-slash');
        });
    });
</script>

UniSchedule/Views/Home/ThongTinCaNhan.cshtml
@model UniSchedule.Models.GiangVien

@{
    ViewBag.Title = "Thông Tin Cá Nhân";
}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6 col-lg-5">
            <!-- Giới hạn chiều rộng đẹp hơn -->
            <div class="card shadow-lg rounded-4">
                <div class="card-header bg-primary text-white text-center rounded-top-4">
                    <h4 class="mb-0"><i class="bi bi-person-vcard"></i> Thông Tin Cá Nhân</h4>
                </div>
                <div class="card-body px-4 py-3">
                    <dl class="row gy-2">
                        <!-- gy-2 tạo khoảng cách giữa các dòng -->
                        <dt class="col-5 text-muted text-end">Mã giảng viên</dt>
                        <dd class="col-7 fw-semibold">@Model.MaGV</dd>

                        <dt class="col-5 text-muted text-end">Họ tên</dt>
                        <dd class="col-7">@Model.TenGV</dd>

                        <dt class="col-5 text-muted text-end">Email</dt>
                        <dd class="col-7">@Model.Email</dd>

                        <dt class="col-5 text-muted text-end">Số điện thoại</dt>
                        <dd class="col-7">@Model.SoDienThoai</dd>

                        <dt class="col-5 text-muted text-end">Khoa</dt>
                        <dd class="col-7">@Model.Khoa.TenKhoa</dd>
                    </dl>
                </div>
                <div class="card-footer bg-light text-end rounded-bottom-4">
                    <a href="@Url.Action("GiangVien", "Home")" class="btn btn-outline-secondary">
                        <i class="bi bi-arrow-left-circle"></i> Quay lại
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>